ansiblepull_present: true
ansiblepull_cron_minute: "0"
ansiblepull_cron_hour: "*"
ansiblepull_workdir: "{{ ansible_path }}"
ansiblepull_script_name: ansible-pull-full.sh
ansiblepull_lockfile_name: ansible-pull-full.lock
ansiblepull_initial_installer_lockfile_name: .ansible-galaxy-installed.lock
ansiblepull_install_pull_cron: true
ansiblepull_password_file: "{{ ansible_vault_password_file }}"
ansiblepull_repo_url: https://github.com/awfulwoman/home
ansiblepull_playbook: "{{ ansible_hostname }}"
ansiblepull_run_after_wake: false
