- name: ZFS and backup stuff
  hosts: belinda
  roles:
    - role: system-zfs
    - role: system-zfs-policy
    - role: backups-zfs-server
  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
