# code: language=ansible

# Only include values that are used everywhere!
vault_wifey_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63613964643037316438366164353939393964653738626137643033353839653063363835356138
          3566623661613934373431333263323966326565376332330a646234653266333335323764346562
          63653430316231383465643733383731656636376363343539633665313739333432323737353563
          3635343337313039370a666434663536663039333562366539363436356662386233363563616632
          6463
vault_olddomain_se: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38383637346431633463643935306664636635323131663732323936656537626138663863396163
          6638323936316362333366396338316533303939663439370a346339343430353438326539353136
          33393835636634663162616430666664303365386231363836353739323838336635636361333135
          6562343337306665330a646133356366363435363766613865643465346663623263633562316263
          62336632386266333763323165333232643139383032323863643432386331613532
vault_infra_domain_name_ew: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64303266333666663436636637383462366639653238373935656537396538353964613032383637
          3863653539653461356534393237636230393565353464640a363731323735353137326161393136
          63326663626231353930633663366661643565386531373732383033653762396336306232356464
          3330623165653135360a343430343139326661306131633438656233313637653666636531653566
          6332
vault_infra_domain_name_rs: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38653663623464323166346234303430306433393834636164383634666635386561323036366633
          6238666231656631383164383632363237336136353235300a636564623632643736356461313139
          39613062346266656162343338356262373333633437383565346262623966326432303134613165
          3162333566316637610a323961326163666234643533393532343862663664353331653737323733
          3766
vault_domain_test: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65626635353937663136626135303131623038646430623864323566313831383634656562666532
          3063346566366363323233346130616535313963633863340a333432633266313637396161653537
          66626539336361666237373565316137303438363438636637613666623762336663386265633430
          3134646462366230330a663939316465376162306333623232613064636336623239373065346433
          6639
vault_olddomain_wc: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62373661373439386434376139323439313062616636366366383364326431363063363831666534
          6666373163393631346230343335313134663133303361640a623632333232663734313066336364
          64626131656166636134336436346535343930623637336262366530666562643166353264363166
          6134623230613738650a656133666536633534383866306333376331643739386333356662303439
          3362

domain_name: "{{ vault_infra_domain_name_ew }}"

# vault_vagrant_public_key:
# vault_vagrant_private_key:
