vault_zfsbackup_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          66656566356238633835316430363561323763333732633732613835396663663039333361323138
          6530613661353130386237383666613739653336323365610a366130656638656465666361336133
          66663862646464303531353635343863646630643739656537326231636366353161373261376638
          3963613439393764630a643135613833396161333539383933366531646339623834326439376266
          34313862663433323138623566626232353936643062633435306634666330613664616263343337
          32366466353363306538363235386262653830313162386536366534336635366433316332366461
          356336336636373063396533623362613332

vault_zfsbackups_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31666265393334626463386132626366396432373932393233313437336537333465323231656430
          3038646137656634346163646163343838356637393731630a323561356534393437646230323133
          63336564613838653561306365333663306666336639373739383831633631353537316636303438
          3865656163303237650a353932326661336363386366356166353262663561616232323335383835
          3034

vault_zfsbackups_privatekey_b64: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32613366383435653538376561363331653737383761306566653133323565346236313035666536
          3133633233383739326232376330343731643832373236300a666463393832616361626666396430
          36666463373838313736373133373561326261656530303762613461623462316661393134326438
          3937656530353165350a633466656536323232313163393462393332306366396464323563643038
          36396239306535383639626464386132343164633932383864386339663535663033636566383133
          31393737383035343665666339363030356131613537333733323438353239306232646436636362
          30346163326236356166303937396565656465336237336565373134663962333731626431326131
          38376237613465636366623164346364333661333065323639656130396562363261363638326330
          61373865326466326164636634393533393332373831653335613030396435346537366139356165
          32353536393531343261336435656330353266323338333638306164363136333461616337313035
          39336466646439653264656265663134353737363162643232316437643332363732646265323964
          66313836646637616563633565623165643762663861653264363766613133303764336134306430
          65306465323035383132306534626264353135613830323861386630323765663634643335336662
          30313331373337626236633266643438306231366631646365316632643165393539646134646366
          66303034653934353736393535623731386233623832393531663433653031623238396361633763
          62656166643466386236363939313766636436613663636538656335613834666432346339323430
          66303232663830353732336430323434313835646237613730366564303735366661346461363861
          61633738386561333662386232636433623838656162616431353330326261396639356165353636
          36666633636363353830303630646635396431663765353262643131623562653834653632366263
          62633839333532633664333265323330303761363761303535643739373934663235636137646237
          37323732373162316331303131333664653535313961353762343830643064323139343134376365
          66363739656138376162663237393435376163626262386364663630633562663638383738363431
          30353535663236646137643862663436343639636336353437623163653333343764353732373330
          32333964363337373066313438613362623130313731643863383764313061343464646662383632
          39313564393463353030383034316434623034616464613630316465643836326431303438643533
          39613666656439383732646637326336616237363632613563343234366531313564333364306264
          63303730396338666436623861303435303431646565623333376362333664313963353937623335
          32323563623261663864343761626336346636386562633031373966616166393932376161336435
          65396365363733343964653061626639646330316466613739656134613836646336656437623638
          61653362303264613964356238663836613361636633623234643163313063303332326165333734
          63376135653830383437613433346161643965356230616431666639626434383565373163313739
          31353935376530336338393639653630373265323561386135383132653535393736363630393062
          30613534643934343965663537643533396361636534613163623263366532663533313139386330
          37646636373236633366636463623231333961396637663735633737636462313031373963356361
          62316633323938633463636339376164663531656239616134616266326433376333633164363866
          66383433653831323764656331353930386266623566643030303231663939363534376535333261
          65393666663366636637393338353162376638383266343532396661633364356562623436613963
          32363331353337396534396364643565616462373765613839363231636165356335666230363338
          35363538616337353234663531383932323030623265623565613738373965336637376335343730
          38633135653135383434393137363561613362396239393366666366386332633133623765303063
          36656661653137616563383530623265623337333932623261356663383135646336373863366265
          65303263616362353434653138626634316131373536313332306364303665336636313033373463
          30343932356637356564326232623232386361353931303761383830323861343532323037313062
          61343333363161666138396365366462636562373938326235356466356438363331386531316261
          36663663343464363461626362306432323637363164303661656565306130393664633935346131
          61636338306631363232646532653238613832383465363261336233326538333562383831376434
          32393335383830316330303236303761323065366262633834346134373762376633616638623935
          35333065636132373334366638633934666464356431666230333030373465373466336331326462
          64383463363439643437353963653963626138633964343536326535343063656238623033336633
          64333866633836333734653130383630323936373532303731656339343766663837323365626464
          32613064366234396438323864616163306530373863343838313439646337396539363365306363
          32383235373233653631323364363563373232323263356539313865326132643837313332656364
          31663633363266323762613066363261613162663536336561626533626163393432323637653533
          36326234343364666234343933653061663137343634336564383631663736326138303337643832
          61326130356138343239323734323133636664303635666133323436633133366634626435613632
          38646638663330356439313961313932646436396562336337613762383365363930313637323434
          66303435653138616561613837326265656339306166323363633437396231393965396664633531
          32666531363765353237366138663237333331366663623764353763623961616639326366666463
          31393065316339346661366533653535633964643437646339386138623962636130326666373164
          30323531366365363935643439323864376666396339323738353566303938353036366531326231
          33383966313932373736353237313239323433653237656238393737396531656130646662366164
          63396536333839326264663432393338636365363239626166386432316339373933373138343234
          63663365343139303165303262363330313239356364623831643237616365663135633839333535
          35306562336530346537613765626232643831373734323864626164303637313166323036316366
          35326563333734323335373130643336376162376463356536356234653535636635326162623266
          62633739383266346536343365336531303662393036323030303835346535346631323433353763
          61616635393762343665623930343630313461333534323737633466346262623032353963303639
          65393830396632633531663463313238643030366533363233613330306362373933643639636464
          38653138333937656633663665373633313430643831643033343333333262613061303964306536
          37633265336139383434653264366262326666626638333330313035363762663938323139326632
          62643734653666653339343135303834633434333261346364396263376164323864376230353239
          32643033356461376433626161643532316132326363336639626139393835323233666136333865
          63383132646335636535313932323932623133356466363534306462343163616435613032636264
          64303334653937363466383163353737323336303433623462333838666132643262376332376461
          66363266376237373231636163393561306433343935313233316361336537363632306534373634
          65326335396430373437626633613065316136666663313833396237613239376131316539316238
          64653066653164313938613037343238386333613338613231646231623034306562306237653261
          65326166333836633338383331626632646664376636376234353331303366323933363237376333
          35386266316361323330346661303531316339393563326431663739363863643263363066383231
          62303135343535386563663034633339623630363365366562643539343432666661353935366561
          39626161353833393862383235356664343639303639613062353562386331633938623332633465
          62326337613832396131373935313366616438333835333065666636323330343235303562306633
          34633564656332313734326339363137316535303934623864623231323566626230393438633532
          63373131323236353238353831363637356630313332613730656161333632656461653766343963
          31386436383231353139646531396631373866346437303639623466366233613064653231316263
          66393363656330633239323139353234303739623733333966613738323232386635383037643564
          37326638323134356237346666636330303032666332323032323137643061336533346135383635
          37363738356263623361393264323832376666663837373232626337336630636332353237386366
          32613663316433633330633336303638376632643965373063373737336463336263313261646564
          64363263363065646363313463336434306664663037383638346636636333616461316331616662
          31643537313561366136373364666334336531303839613935646233346237653765616637373463
          30626638396433393132633736386335346132646639363265353530386230366134643632396663
          30336139616437633237616339626332373061623563323534323231633565336531666535393139
          30356333323966316262636635356635613631383833376466306631613462643431643532316364
          38653633613437323263363266613730313265323862373236306162666535646132666565303634
          34383934643639313462663762306539633361313363356532653465396134373333383136353935
          62376230313133613766336434396631623539656663313038643034393333643062393266356339
          65326139626435653337653431663165363363643633376531316531396539333432386433663664
          64313833326537386638313332393937626130373038643535653131633833656335363564303065
          36313962313166643232633830663464386439663339306332346333373633383839653735323030
          31366337303336346261343936653830343639663239346138383666326632336562613132303739
          64386161633233306639383836373264643438663361326133343539623063373231326337373164
          39363033656337663834636462393831353537353562396662633266343632396636656138366562
          34393331303438376162333762373734303236393031633763303130393437313763653334383261
          38623231633736336336656432393534386534343366666432376565383664386465343130363934
          38633564646532656561333133313735656663653937623831616464323134636663343737323237
          63386239626562633561396431623639613661616665666566343230336361326535326333353336
          65623061643066313134303732643037306430376137366563613038653033393335376538373139
          32643031336636346438653833663931376437336437396230303761393437643832346462353030
          38306336353264653466313461343163613537636162393131613165386464653237646135323335
          39616662653661653830656230333065336130383163663339613939363635623764623337666239
          32366165643963336133353436646138666566386662303131316439613831626566383533346330
          63623966323266336334613231376262626539376166643664656330356264653635636536343264
          63666532346536656163623235363438613336376664316461383963633061643630306364323037
          31333365663934656166303637396235336431623435653032383563646638396265303530643265
          32356137333037383932616464623261623161326662306336363130613433646232633239306133
          64363065356165343331333738353230646439363531303230336137353464316539643162356338
          62343530663261313664306662306335313666663134303164323130643065356531336662613835
          36343662393237666637303131623432633932653764333934633630303934653766313463666430
          37663765623363373163343362343330663337343035333866343935356530336534623066626364
          31636365653762613939663536343538373765373865346639303333393630613535343033646631
          33643261643530343139316130366231666662313131376461626132323439306531646366356462
          62653030326632666534373039663036326162376662646330346334303631353730386137343832
          36336335393535373166306333316531396335623333383432613965313761636564646535353230
          32383630383165656534636666326564383538383830393233373839666637663038

vault_zfsbackups_public_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62646336356638616161616466306434623064313235323934633565393336623965396363656262
          6361636139383766656161353266643737363163343664630a323037616162306333303937663434
          33633834303631323337396138636434656537636166306137306366396231633537336537653166
          3137376666643635380a633163323539643634376666366636653261363938616435393833633535
          34313366616337353837363939366664613064303265653734666339623966316230653337633635
          39626563383735653235643337393564373139393637343637376335363133363036333864353061
          31636464353964326561316137356435303439333335393634306239626534643665393535623631
          64633432623961373137626230363364376536326538376334616635646364396532336663663230
          36383164373663633432666235316561303336626237353665373465626535366661303338646665
          33666331336331643033666462613934373639633636343964323763323463343662343865623630
          65666438346331613138306532326363643933313738613032653835646437333237356433383661
          31326335616262346232633238313035346537646362313965353436666436613266336139316534
          63376633353536623336643330636338646163303063636530616331316531343737633333313765
          64336232616433353862353462363430623764653264333636386433626137333738636239326462
          31306263613733353965346333663165363631336163336138393939373637326164616466333036
          33303964396265323931333133363463613764636266386234633033636362636432626333306339
          36353035376633333035646665356131373637643064393663613932376164393131623037393166
          31623735656266616238393831303663386331653065323831393235643137326432623332653466
          64303731326264653364316465316337353938356663396162333266613566643132663632363261
          30623266326339633337353739653466653561663663383331663137636336343761623736343332
          38613265373438366161363931303239363038363265393564336231373033363236653231316562
          38653231386235303461336334396465343939636365623430336531386666346464613965373466
          65393562313063383461353064356135623664333266333935376536653436663335653266353065
          34373639363430613536
