---
- name: UK Server (compositions only)
  hosts: host-albion
  roles:
    - role: composition-reverseproxy
    - role: composition-container-management
    - role: composition-zfs-api

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
