- name: UK Server
  hosts: host-albion
  roles:
    - role: hardware-raspberry-pi
    - role: bootstrap-ubuntu-server
    - role: infothrill.nullmailer
      become: true
    - role: system-sshkey
    - role: system-zfs
    - role: network-ip-address-forwarding
    - role: client-nfs
    # - role: backups-zfs-client
    - role: backups-zfs-archive-offsite
    - role: compositions
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
