- name: UK Server
  hosts: host-albion
  roles:
    - role: hardware-raspberry-pi
    - role: bootstrap-ubuntu-server
    - role: network-netplan
    - role: infothrill.nullmailer
      become: true
    - role: system-sshkey
    - role: system-zfs
    - role: backups-zfs-archive-offsite
    - role: network-ip-address-forwarding
    - role: client-nfs
    - role: composition-reverseproxy
    - role: composition-container-management
    - role: composition-zfs-api
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
