- name: UK Server (dev work)
  hosts: host-albion
  gather_facts: false
  roles:
    # - role: compositions
    - role: backups-zfs-archive-offsite

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
