vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          31666330386162316536396366363564356135353739383031383265326666656533663932313037
          6365363865363630383763346238356132303330663565640a393230623833633361303937613661
          39373335633734366166343139643966663966336433326132373836653233363066373636643532
          3031333736306433650a646433633330613864643836313962373834623633636163646432636263
          36306563383337313066316236643938646337616535626531663437623265383163333764616139
          3533653161373331373235376330323739623061326464353832
