vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          36313263376535323561323738323365373932393933616630643861306363356635656530613636
          6665663630366265643933633963336661643432303562650a316235346239376535303634643239
          37336663356666303064626539636438633930636439313336653633646130346331396263373066
          6636653531626534610a333762643635303438633737393232356539323639623665623230623230
          6632
