- name: Install MQTT tools
  become: true
  ansible.builtin.apt:
    name:
      - mosquitto-clients
    state: present
    update_cache: false

# Copy script to controller
- name: Copy script
  become: true
  ansible.builtin.template:
    src: mqtt2cmd.sh.j2
    dest: "{{ mqtt2cmd_executable_path }}/{{ mqtt2cmd_executable }}"
    owner: root
    group: root
    mode: 0755

- name: Ensure shutdown without sudo password
  become: true
  community.general.sudoers:
    name: allow-shutdown
    state: present
    user: "{{ ansible_user }}"
    nopassword: true
    commands: /usr/sbin/shutdown

- name: Ensure suspend without sudo password
  become: true
  community.general.sudoers:
    name: allow-suspend
    state: present
    user: "{{ ansible_user }}"
    nopassword: true
    commands: /usr/bin/systemctl suspend

- name: Ensure reboot without sudo password
  become: true
  community.general.sudoers:
    name: allow-reboot
    state: present
    user: "{{ ansible_user }}"
    nopassword: true
    commands: /usr/sbin/reboot

- name: Create mqtt2cmd.service
  become: true
  ansible.builtin.template:
    src: mqtt2cmd.service
    dest: /etc/systemd/system/mqtt2cmd.service
    owner: root
    group: root
    mode: 0664

- name: Make sure mqtt2cmd service is running
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: mqtt2cmd
    enabled: true
