# Composition name (used by composition-common dependency)
composition_name: reverseproxy

reverseproxy_use_letsencrypt: true
reverseproxy_catchall: false
reverseproxy_statuspage: false
reverseproxy_whoami: false
reverseproxy_traefik_domain: "traefik.{{ ansible_facts['hostname'] }}.{{ domain_name }}"
