vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          39323661306363386332636537336134623138343936336161383431646166666434633130383961
          3337383531613862343161313038313361386236636337640a623232613233326236326232633736
          66373462393630363534656263653566653739663230363732336135386438363230663861356436
          3530393336333435350a306231623632663434383733373965303066383966316638623732666439
          61393434623766383234633032623164653237643865646436313265313432393339363662663238
          3932393366386665333961656363313165666437363962353936
