ansible_host: host-guineacam
ansible_user: "{{ vault_server_username }}"

# --- NETWORK -------------
configure_dns_linkdevice_physical: "eth0" 


# --- COMPOSITIONS -------------
compositions_config_dir: "/home/{{ vault_server_username }}/compositions"

compositions:
  # - reverseproxy
  # - container-management
  - testcam

