ansible_user: ubuntu
ansible_host: host-backups.i.affordablepotatoes.com

wakeonlan_mac_address: "60:a4:4c:40:52:57"

# Base for all container dirs. Normally on an SSD.
container_config_dir: /opt/containers

# Healthceck.io
healthcheck_reboot_id: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          66303638323166346639366633633432343033653536346639626333643734613062323135396366
          3662393232623234386265623139316330303239323138380a636565386563306234373066646232
          63356537363537393366336630646566646134633930326636313033376631656565633239323462
          3431363431343934370a383030336238373665623334323331643033313962343435643337613762
          61633265323161656365333764363436623863626465666131366635383733353334323233666661
          3639336261666139616332376534376634663132393532643166
