linux2mqtt_executable_path: "{{ pip_virtualenv_bin_path }}/linux2mqtt"
linux2mqtt_service_path: "{{ systemd_service_path }}/l2m.service"
linux2mqtt_params: "--host=mqtt.{{ domain_name  }} --name={{ ansible_facts['hostname'] }} --cpu=15 --vm --temp --fan --du='/' --net={{ configure_dns_linkdevice_physical }},15"
