# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: dns
ansible_user: "{{ vault_server_username }}"

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: baremetal
host_name: dns
host_city: ber
host_location: xberg
host_ipv4:
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"

# -------------------------------------------------------------------
# UBUNTU
# -------------------------------------------------------------------
ubuntupro_attach: true

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_bluetooth: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
configure_dns_linkdevice_physical: "eth0"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    datasets:
      compositions:
        importance: critical
        inherit_policy: true
        datasets:
          awfulwoman:
            importance: none
          container-management:
            importance: none
          reverseproxy:
            importance: none
      acme:
        importance: critical
      terraform:
        importance: critical

# -------------------------------------------------------------------
# MISC
# -------------------------------------------------------------------

acme_path: "/fastpool/acme"
terraform_working_dir: "/fastpool/terraform"

# -------------------------------------------------------------------
# COMPOSITIONS
# -------------------------------------------------------------------
reverseproxy_use_letsencrypt: false
compositions:
  - reverseproxy
  - container-management
