vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          61393765656637633233333034373063616465316234663032313463643334386332343133666633
          3661643363613434326361646366613961343663326335320a363137323334653663313833613130
          38386562653964323364623336333235336661383961366463616663613435393963383565323938
          6466613961666532330a343738333338646430643736303430386366626531353565633335316531
          3066
