- name: ZFS Basics
  import_playbook: basics.yaml
- name: ZFS Backup Clients
  import_playbook: clients.yaml
- name: ZFS Offsite Servers
  import_playbook: offsite.yaml
- name: ZFS Backup Servers
  import_playbook: servers.yaml
