# Deactivate role
- name: Deactivate Cron
  become: true
  ansible.builtin.cron:
    name: "Auto-suspend"
    state: absent
  when: sleepuntil_active is false

- name: Remove script
  become: true
  ansible.builtin.file:
    dest: "{{ sleepuntil_script_path }}"
    state: absent
  when: sleepuntil_active is false


# Activate role

- name: "Remove any traces of old .sh script"
  become: true
  ansible.builtin.file:
    dest: /usr/local/bin/sleepuntil.sh
    state: absent

- name: "Copy sleepuntil script"
  become: true
  ansible.builtin.template:
    src: sleepuntil.sh.conf
    dest: "{{ sleepuntil_script_path }}"
    mode: "0755"
  when: sleepuntil_active

- name: Cron to auto-suspend in early hours
  become: true
  ansible.builtin.cron:
    name: "Auto-suspend"
    hour: "{{ sleepuntil_autosleep_time_hour }}"
    minute: "{{ sleepuntil_autosleep_time_minute }}"
    job: "{{ sleepuntil_script_path }} -T {{ sleepuntil_sleep_time }}"
    state: present
  when: sleepuntil_autosleep and sleepuntil_active

- name: Allow the root user to sudo /usr/sbin/rtcwake with no password
  become: true
  community.general.sudoers:
    name: allow-rtcwake
    state: present
    user: "{{ ansible_user }}"
    nopassword: true
    commands: /usr/sbin/rtcwake

- name: Allow the root user to sudo /usr/bin/killall with no password
  become: true
  community.general.sudoers:
    name: allow-killall
    state: present
    user: "{{ ansible_user }}"
    nopassword: true
    commands: /usr/bin/killall


# TODO: Listen for sleepuntil MQTT message
