- name: Add a jaunty little Grub tune
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    line: GRUB_INIT_TUNE="1750 523 1 392 1 523 1 659 1 784 1 1047 1 784 1 415 1 523 1 622 1 831 1 622 1 831 1 1046 1 1244 1 1661 1 1244 1 466 1 587 1 698 1 932 1 1195 1 1397 1 1865 1 1397 1"
    regexp: "#?GRUB_INIT_TUNE="
    state: present
  register: grub

- name: Rebuild grub
  become: true
  ansible.builtin.command: update-grub
  when: grub.changed
