vault_splitwise_admin_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          31373932313864323433366465333631303936393661323965313433313233326464643563653732
          3038383638333439323739366663383830376336366335360a373066373435396464346636386637
          66323434323831653066636135343266353965336635336335383134336331636337633530613037
          3463616333363238660a323030336564656637323561316439613538306332303039643863656135
          6233
