---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Home Automation:

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- Access Points:
    - My Third Service:
        href: http://localhost/
        description: Homepage is ðŸ˜Ž
