---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
title: Home Automation
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
target: _self