- name: Ensure installation dependencies exist
  become: true
  ansible.builtin.apt:
    name:
      - software-properties-common

- name: Add Ansible repo from PPA
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:ansible/ansible'
    codename: "{{ ansible_facts['distribution_release'] }}"
    update_cache: true

- name: Install Ansible from Ansible repository
  become: true
  ansible.builtin.apt:
    name:
      - ansible
      - ansible-lint
    state: present
