- name: Out on the internet server
  hosts: sites
  # vars:
  #   compositions:
  #     - awfulwoman
  roles:
    # - role: compositions
    - role: system-zfs
    - role: system-zfs-policy

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
