- name: Ansible facts
  ansible.builtin.debug:
    msg: |-
      ansible_facts['os_family'] - {{ ansible_facts['os_family'] }}
      ansible_facts['distribution'] - {{ ansible_facts['distribution'] }}
      ansible_facts['distribution_file_parsed'] - {{ ansible_facts['distribution_file_parsed'] }}
      ansible_facts['distribution_file_path'] - {{ ansible_facts['distribution_file_path'] }}
      ansible_facts['distribution_file_variety'] - {{ ansible_facts['distribution_file_variety'] }}
      ansible_facts['distribution_major_version'] - {{ ansible_facts['distribution_major_version'] }}
      ansible_facts['distribution_release'] - {{ ansible_facts['distribution_release'] }}
      ansible_facts['distribution_version'] - {{ ansible_facts['distribution_version'] }}

- name: Install python3 on Debian
  become: true
  ansible.builtin.apt:
    name:
      - python3-debian
    state: present
  when: ansible_facts['distribution'] == "Debian"

- name: Add repo using key from URL (Debian)
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/debian"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: >-
      {% if ansible_facts['architecture'] == 'x86_64' %}amd64
      {% elif ansible_facts['architecture'] == 'aarch64' %}arm64
      {% else -%}ansible_facts['architecture']{% endif %}
    signed_by: "https://download.docker.com/linux/debian/gpg"
  when: ansible_facts['distribution'] == "Debian"

- name: Add repo using key from URL (Ubuntu)
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: >-
      {% if ansible_facts['architecture'] == 'x86_64' %}amd64
      {% elif ansible_facts['architecture'] == 'aarch64' %}arm64
      {% else -%}ansible_facts['architecture']{% endif %}
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Docker from Docker repository
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: "Ensure user is in docker group"
  become: true
  ansible.builtin.user:
    user: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset connection so shell is picked up.
  become: true
  ansible.builtin.meta: reset_connection

- name: Ensure /etc/systemd/system/docker.service.d/ exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy daemon.json
  become: true
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Docker

- name: Copy override.conf
  become: true
  ansible.builtin.template:
    src: docker.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    force: true
  notify:
    - Restart Docker

- name: Ensure ufw port is open
  become: true
  ansible.builtin.copy:
    src: "docker.ufw.profile"
    dest: "/etc/ufw/applications.d/docker.ufw.profile"
    owner: root
    group: root
    mode: "0664"
  notify: Restart ufw
  when: docker_port_open | default(false) | bool
