- name: Add Wake-on-LAN service
  become: true
  ansible.builtin.template:
    src: templates/wol.service.j2
    dest: "{{ wakeonlan_destination_path }}/{{ wakeonlan_destination_filename }}"
    owner: "{{ wakeonlan_destination_owner }}"
    group: "{{ wakeonlan_destination_group }}"
    mode: 0774
  notify:
    - Restart wol

- name: Start service if not started
  become: true
  ansible.builtin.service:
    name: wol
    state: started
