---
- name: Deploy Promtail to all Docker hosts
  hosts:
    - host-storage
    - homebrain
    - deedee
    - host-backups
    - host-albion
    - belinda
    - sites

  roles:
    - role: system-promtail
