---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - airflow
      - alfred
      - balenaetcher
      - docker
      - firefox
      - google-chrome
      - handbrake
      - home-assistant
      - imageoptim
      - mullvadvpn
      - raspberry-pi-imager
      - remarkable
      - send-to-kindle
      - telegram-desktop
      - visual-studio-code
      - vlc
      - whatsapp
      - discord
    brew_packages:
      - ffmpeg
      - flux
      - get_iplayer
      - git
      - helm
      - jq
      - kubectl
      - macvim
      - mutt
      - neofetch
      - transmission-cli
      - nmap
      - rsync
      - sqlite
      - watch
      - wget
      - youtube-dl
      - yq
      - mas
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

  tasks:
    - name: Updating Homebrew
      community.general.homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists


    # - name: Upgrading Homebrew Packages
    #   community.general.homebrew:
    #     upgrade_all: "{{ upgrade_homebrew_packages }}"
    #   register: result
    #   until: result is successful
    #   when: homebrew_check.stat.exists

    - name: Installing Homebrew Casks
      community.general.homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists