- name: Home Automation Server
  hosts: host-homeassistant
  roles:
    - role: bootstrap-ubuntu-server
    - role: network-netplan
    - role: system-zfs
    - role: system-zfs-policy
    - role: infothrill.nullmailer
      become: true
    - role: server-nut
    - role: system-mqtt2cmd
    - role: hardware-rtl-433
    - role: backups-zfs-client
    - role: system-beep
    - role: system-shoutrrr
      become: true
    - role: composition-reverseproxy
    - role: composition-container-management
    - role: composition-homeassistant
    - role: composition-matter
    - role: composition-owntracks
    - role: composition-mqtt
    - role: composition-zigbee2mqtt
    - role: composition-watchyourlan
    - role: composition-zfs-api
    - role: monitoring-healthchecksio
    - role: system-promtail

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
