- name: Home Automation Server
  hosts: host-homeassistant
  roles:
    - role: bootstrap-ubuntu-server
    - role: system-zfs
    - role: system-zfs-policy
    - role: infothrill.nullmailer
      become: true
    - role: server-nut
    - role: system-mqtt2cmd
    - role: hardware-rtl-433
    - role: backups-zfs-client
    - role: system-beep
    - role: system-shoutrrr
      become: true
    - role: compositions
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
