---
- name: Home Automation Server NEW
  hosts: host-homeassistant
  vars:
    compositions:
      - watchyourlan
  roles:
    - role: compositions

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
