---
- name: Dev stuff
  hosts: host-homeassistant
  vars:
    compositions:
      - container-management
  roles:
    - role: compositions

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
