# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: 192.168.1.112
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: baremetal
host_name: samson
host_city: ber
host_location: xberg
host_ipv4: 192.168.1.112
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"

# -------------------------------------------------------------------
# UBUNTU
# -------------------------------------------------------------------

ubuntupro_attach: false

# -------------------------------------------------------------------
# BOOTSTRAP
# -------------------------------------------------------------------#
bootstrap_ubuntu_timezone: "Europe/Berlin"

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_bluetooth: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
host_primary_interface: "eth0"
# configure_dns_linkdevice_physical: "eth0"
tailscale_exit_node: true

# -------------------------------------------------------------------
# REPOS
# -------------------------------------------------------------------
repos:
  - url: https://github.com/awfulwoman/infra
    name: infra
  - url: https://github.com/awfulwoman/obsidian
    name: obsidian

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    vdevs:
      - type: stripe
        disks: /dev/disk/by-id/usb-USB_SanDisk_3.2Gen1_0501f56e8b204d273e4fefdd60408eefbbb1a99d524666fc3243c7d31f73791ef10200000000000000000000708c093200920b10915581071f2f4514-0:0
    datasets:
      compositions:
