vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          30303231626336383239613535666138306637366666313161613830656436643161346236356466
          3937353363656638623563633234343635373436346538620a376261623034336661633564343864
          31303465346538653631306434613137643233356531653031663535323164396530356233396238
          6665386131346165300a356233643162303737333736303365363462393237323431356263663431
          61313064393531396237386663626639616465313334356162643131343335336161326635346564
          64323762336136303764383133323339376232616462643463343936316564653765386230303837
          35333138643562616563333531343462626132343164646531633138633732363833396431663763
          38323966386565633236

vault_zfs_passphrase: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          32303436643438333862313134616130636161376566363564346632616632306162636234616262
          6430303334346438666263303533663362636262336633350a393464656264396162643135383439
          64313261393062333135613633326163323166393433653862366130393135613436626165643134
          3139663566376264330a333738333732333261343930646366666139356334663265353061343164
          65333737646138333465376631653931316131316164326338396262393364633038643234646331
          32656634396636643231393333613261376364626637366261363262393764626263303734656334
          36626233613833623166323430646637666631343039323965636465646163663236373430373161
          34366236643837326538
