# code: language=ansible
- name: Create compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ composition_root }}/docker-compose.yaml"

- name: Create .env files
  ansible.builtin.template:
    src: environment_vars.j2
    dest: "{{ composition_root }}/.environment_vars"

- name: Create backup directories
  ansible.builtin.file:
    path: "{{ composition_config }}/{{ backup_item }}"
    state: directory
  loop_control:
    loop_var: backup_item
  loop:
    - config
    - log
    - data

- name: Copy over config file
  become: true
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: "{{ composition_config }}/mosquitto.conf"

- name: Run Configure DNS role
  ansible.builtin.include_role:
    name: "configure-dns"
  vars:
    configure_dns_subdomains:
      - mqtt