- name: VM Media
  import_playbook: vm-media/core.yaml
  tags:
    - private-infra
- name: VM Home Automation
  import_playbook: vm-homeautomation/core.yaml
  tags:
    - private-infra
- name: VM Downloads
  import_playbook: vm-downloads/core.yaml
  tags:
    - private-infra
- name: VM Claude Dev
  import_playbook: vm-claude-dev/core.yaml
  tags:
    - private-infra
- name: VM Hetzner
  import_playbook: vm-awfulwoman-hetzner/core.yaml
  tags:
    - public-infra
