---
# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: 192.168.122.12  # Internal NAT network
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"
ansible_ssh_common_args: '-o ProxyJump=host-storage'

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: virtual
host_name: downloads
host_city: ber
host_location: xberg
host_ipv4: 192.168.1.202
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"

# -------------------------------------------------------------------
# STORAGE
# -------------------------------------------------------------------
shared_media_path: /slowpool/shared/media

nfs_mounts:
  - remote_server: 192.168.122.1  # host-storage NAT gateway IP (internal network)
    remote_path: /slowpool/shared/media
    local_path: /slowpool/shared/media
