---
# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: 192.168.1.202
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: virtual
host_name: downloads
host_city: ber
host_location: xberg
host_ipv4: 192.168.1.202
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"

# -------------------------------------------------------------------
# STORAGE
# -------------------------------------------------------------------
shared_media_path: /slowpool/shared/media

nfs_mounts:
  - remote_server: 192.168.1.116  # host-storage local IP (avoid Tailscale overhead)
    remote_path: /slowpool/shared/media
    local_path: /slowpool/shared/media
