vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          33363363303732666234343836393961303034303863393233666330623632326336323362323562
          3534313138336231616631383339356531313762663462300a366364613864356236366463383863
          30393131633561626133633934303332316339343631313265336361643438353432383966613935
          3132343461323135350a326163303763333438636436663165386466623737646533623739363263
          37653435626565353361356335336137366530663730656236326363333331323462336236616162
          6463343966643031646462313863663938313332353862376532
