zfsbackup_cron_hour: "10,12,16,20,0"
zfsbackup_cron_minute: "0"
zfsbackup_logging_dir: /opt/zfsbackup/logs
zfsbackup_logging_successfile: backups.log
zfsbackup_logging_errorfile: error.log
zfsbackup_script_path: /opt/zfsbackup
zfsbackup_dataset: backuppool/encryptedbackups
zfsbackup_pull_group: zfs-backup-clients # The ansible group that we try to pull backup data from
