- name: DNS
  hosts: dns
  roles:
    - role: hardware-raspberry-pi
    - role: bootstrap-ubuntu-server
    - role: network-netplan
    - role: infothrill.nullmailer
      become: true
    - role: system-sshkey
    - role: system-zfs
    - role: infra-public-resources
    - role: infra-named
    - role: infra-certbot
    - role: composition-reverseproxy
    - role: composition-container-management
    - role: composition-zfs-api
    - role: backups-zfs-client
    - role: script-share-personal-site
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
