- name: DNS development playbook
  hosts: dns
  roles:
    # - role: weareinteractive.environment
    #   become: true
    # - role: script-share-personal-site
    # - role: infra-named
    # - role: infra-dhcpd
    # - role: infothrill.nullmailer
    #   become: true
    - role: system-zfs-policy

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
