- name: DNS
  hosts: dns
  roles:
    # - role: weareinteractive.environment
    #   become: true
    # - role: script-share-personal-site
    # - role: infra-named
    # - role: infra-dhcpd
    - role: infothrill.nullmailer
      become: true

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
