- name: Update Terraform
  hosts: dns
  roles:
    - role: infra-public-resources
    - role: infra-private-resources

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
