- name: DNS Server - ZFS API
  hosts: dns
  vars:
    compositions:
      - zfs-api
  roles:
    - role: compositions

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
