- name: Backup Server
  hosts: host-backups
  roles:
    - role: bootstrap-ubuntu-server
    - role: network-netplan
    - role: client-nut
    - role: infothrill.nullmailer
      become: true
    - role: system-wakeonlan
    - role: system-zfs
    # - role: system-msmtp
    - role: system-mqtt2cmd
    - role: backups-zfs-server
      zfsbackup_pushover: false
      zfsbackup_run_after_wake: false
    - role: composition-container-management
    - role: composition-reverseproxy
    - role: composition-zfs-api
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
