- name: Backup Server
  hosts: host-backups
  roles:
    - role: bootstrap-ubuntu-server
    - role: client-nut
    - role: system-wakeonlan
    - role: system-zfs
    # - role: system-msmtp
    - role: system-mqtt2cmd
    - role: server-zbackups
      zfsbackup_pushover: false
      zfsbackup_run_after_wake: true
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
