- name: Backup Server (dev work)
  hosts: host-backups
  gather_facts: true
  roles:
    - role: system-zfs-policy

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
