- name: Backups Server - ZFS API
  hosts: host-backups
  vars:
    compositions:
      - zfs-api
  roles:
    - role: composition-container-management
    - role: composition-reverseproxy
    - role: composition-zfs-api

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
