# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: "192.168.1.130"
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: baremetal
host_name: homebrain # Hostname of the machine
host_city: ber # City where the machine is located
host_location: xberg # Location of the machine within the city
host_ipv4: 192.168.1.130
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"

# -------------------------------------------------------------------
# UBUNTU
# -------------------------------------------------------------------

ubuntupro_attach: true

# --- NETWORK -------------
# configure_dns_linkdevice_physical: "enp1s0"
network_interface_primary: "enp1s0"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    device: /dev/disk/by-id/scsi-SATA_INTENSO_SSD_AA000000000000001079
    datasets:
      compositions:
        state: present
        importance: critical






# ZFS pools
zfs_pools:
  - fastpool

# Named ZFS datasets
container_config_zfs_id: fastpool/containers
container_compositions_zfs_id: fastpool/compositions
syncthing_data_path_zfs_id: fastpool/misc/syncthing

# Datasets present
zfs_datasets:
  - "{{ container_compositions_zfs_id }}"
  - "{{ container_config_zfs_id }}"
  - fastpool/misc
  - "{{ syncthing_data_path_zfs_id }}"

# Datasets to be backed-up
# These datasets will be pulled to a backup server
zfs_backup_datasets:
  - "{{ container_compositions_zfs_id }}"

# Define useful paths from ZFS datasets
compositions_config_dir: "/{{ container_compositions_zfs_id }}"
syncthing_data_path: "/{{ syncthing_data_path_zfs_id }}"

composition_motioneye_usbdevice: /dev/video0

docker_port_open: true

compositions:
  - reverseproxy
  - container-management
  - homeassistant
  - matter
  - owntracks
  - mqtt
  - zigbee2mqtt
  - watchyourlan

traefik_providers:
  - homeassistant
  - esphome
  - watchyourlan

cnames:
  - homeassistant.{{ domain_name }}
  - ha.{{ domain_name }}
  - esphome.{{ domain_name }}
  - mctest.{{ domain_name }}
  - lan.{{ domain_name }}
