# ansible-vault encrypt_string "supersecretpassword" --name="vault_whatever"

vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          37336430633835356132323239336462316434333536373964303262303833646236386639373264
          6165363461336461343036646465316234373232366133620a366463653932383364393335646136
          39366132353837653737343533353065613935316535643938626364383839326561653430336365
          6364646266323966310a633338353861343564333834313066333931326666613138373565353662
          65343531353636303965393866376263323434386665313963393163653233306636363234326535
          6431623333333563386538393665303562633636376266646435
