- name: Out on the internet server
  hosts: vm-awfulwoman-hetzner
  roles:
    - role: composition-reverseproxy
    - role: composition-container-management
    - role: composition-awfulwoman

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
