- name: Ensure Terraform repo exists
  become: true
  ansible.builtin.deb822_repository:
    name: terraform
    types: deb
    uris: "https://apt.releases.hashicorp.com"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    architectures: >-
      {% if ansible_facts['architecture'] == 'x86_64' %}amd64
      {% elif ansible_facts['architecture'] == 'aarch64' %}arm64
      {% else -%}ansible_facts['architecture']{% endif %}
    signed_by: "https://apt.releases.hashicorp.com/gpg"

- name: Ensure Terraform is installed
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - terraform

- name: Read Github authorized keys as string
  ansible.builtin.uri:
    url: https://github.com/awfulwoman.keys
    method: GET
    return_content: true
  register: github_keys_string

- name: Ensure Github keys list exists
  ansible.builtin.set_fact:
    github_keys_list: "{{ github_keys_string.content | split('\n') | reject('==', '') }}"

- name: Ensure cloud-init file exists
  ansible.builtin.template:
    src: cloud-init
    dest: "{{ infra_publicresources_terraform_working_dir }}/cloud-init.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Ensure Terraform project working dir exists
  become: true
  ansible.builtin.file:
    dest: "{{ infra_publicresources_terraform_working_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Ensure Terraform files exist
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ infra_publicresources_terraform_working_dir }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - main.tf
    - provider.tf
    - variables.tf
    - versions.tf
  register: tf_files

- name: DEBUG TF files
  ansible.builtin.debug:
    var: tf_files
  when: infra_publicresources_debug

- name: Run Terraform
  when: infra_publicresources_tf_apply
  block:
    - name: Ensure Terraform plan is tested
      community.general.terraform:
        project_path: "{{ infra_publicresources_terraform_working_dir }}"
        state: present
        force_init: true
      register: tf_plan
      check_mode: true

    - name: DEBUG TF plan
      ansible.builtin.debug:
        var: tf_plan
      when: infra_publicresources_debug

    - name: Ensure Terraform plan is applied
      when: (tf_plan.changed) and (not tf_plan.failed)
      community.general.terraform:
        project_path: "{{ infra_publicresources_terraform_working_dir }}"
        state: present
