- name: Home Automation Server NEW
  hosts: homebrain
  roles:
    - role: composition-homeassistant
    - role: composition-matter
    - role: composition-mqtt
    - role: composition-zigbee2mqtt

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
