- name: ZFS and backup stuff
  hosts: homebrain
  roles:
    - role: system-zfs
    - role: system-zfs-policy
    - role: backups-zfs-client
  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
