- name: Out on the internet server
  hosts: vm-awfulwoman
  roles:
    - role: bootstrap-ubuntu-server
    - role: user-site-deployment
    - role: system-zfs
    - role: client-nfs
    - role: compositions
    - role: monitoring-healthchecksio

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
