# code: language=ansible

# Vault variables
vault_server_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30393036363965616337393739376633353433383939303765333234313263326338396634633732
          6263303266396665613361656434613563626633346131390a646536376336643538393536393262
          31666365326164373534306366613936316261366339663864386665326363323862356266656533
          3464623731653966390a623964626431313364613630346365323634363934326230343663303363
          3639

security_autoupdate_mail_on_error: true
security_autoupdate_mail_to: "unattended@localhost"
security_autoupdate_reboot: true
security_autoupdate_reboot_time: 03:00
security_sudoers_passwordless:
  - "{{ vault_server_username }}"

# Locale
config_system_locale: 'en_GB.UTF-8'
config_system_language: 'en_GB.UTF-8'

# Repo
repo_url: https://github.com/awfulwoman/infra
repo_name: infra

# Docker
default_docker_network: guineanet

# Python
default_bin_path: /usr/local/bin
systemd_service_path: /etc/systemd/system

# SSH config for Vagrant
bootstrap_ubuntu_ssh_config_local_networks:
  - host: "192.168.0.*"
    user: "{{ vault_server_username }}"
    strict_host_key_checking: false
    user_known_hosts_file: "/dev/null"
  - host: "100.*.*.*"
    user: "{{ vault_server_username }}"
    strict_host_key_checking: false
    user_known_hosts_file: "/dev/null"

# Environment Variables
# Vagrant VMs don't need production environment variables
environment_config: {}
