defaultSettings:
  # backupTarget: s3://backupbucket@us-east-1/backupstore
  # backupTargetCredentialSecret: minio-secret
  # createDefaultDiskLabeledNodes: true
  defaultDataPath: /storage
  # replicaSoftAntiAffinity: false
  # storageOverProvisioningPercentage: 600
  # storageMinimalAvailablePercentage: 15
  # upgradeChecker: false
  # defaultReplicaCount: 2
  # defaultDataLocality: disabled
  # guaranteedEngineCPU:
  # defaultLonghornStaticStorageClass: longhorn-static-example
  # backupstorePollInterval: 500
  # taintToleration: key1=value1:NoSchedule; key2:NoExecute
  # systemManagedComponentsNodeSelector: "label-key1:label-value1"
  # priority-class: high-priority
  # autoSalvage: false
  # disableSchedulingOnCordonedNode: false
  # replicaZoneSoftAntiAffinity: false
  # volumeAttachmentRecoveryPolicy: never
  # nodeDownPodDeletionPolicy: do-nothing
  # mkfsExt4Parameters: -O ^64bit,^metadata_csum
  # guaranteed-engine-manager-cpu: 15
  # guaranteed-replica-manager-cpu: 15