ansible_host: "{{ hetzner_floating_ip }}"
ansible_user: "{{ vault_server_username }}"

host_type: virtual

bootstrap_ubuntu_timezone: "Europe/Berlin"

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
configure_dns_linkdevice_physical: "eth0"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    device:
    vdevs:
      - type: stripe
        disks:
          - /dev/disk/by-id/scsi-0HC_Volume_104390137
    datasets:
      compositions:
        policy: critical
      sites:
        policy: critical
        datasets:
          awfulwoman:
      shared:

# -------------------------------------------------------------------
# SITES
# -------------------------------------------------------------------

# Define useful paths from ZFS datasets
site_path_awfulwoman: "/fastpool/sites/awfulwoman"
site_path_shared: "/fastpool/shared"

traefik_providers:
  - gotosocial

compositions:
  - reverseproxy
  - container-management
  - awfulwoman
