ansible_host: 188.245.37.81
ansible_user: "{{ vault_server_username }}"

host_type: virtual
host_name: awfulwoman
host_city: fsn
host_location: hetzner
host_ipv4: 188.245.37.81
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"
host_description: "Hetzner cloud server for public services"

bootstrap_ubuntu_timezone: "Europe/Berlin"

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
configure_dns_linkdevice_physical: "eth0"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    device:
    vdevs:
      - type: stripe
        disks:
          - /dev/disk/by-id/scsi-0HC_Volume_104390137
    datasets:
      compositions:
        policy: critical
      sites:
        policy: critical
        datasets:
          awfulwoman:
      shared:

# -------------------------------------------------------------------
# SITES
# -------------------------------------------------------------------

# Define useful paths from ZFS datasets
site_path_awfulwoman: "/fastpool/sites/awfulwoman"
site_path_shared: "/fastpool/shared"

traefik_providers:
  - gotosocial

# compositions list moved to playbook (see playbooks/virtual/vm-awfulwoman-hetzner/core.yaml)
