---
- name: Install ZFS tooling
  become: true
  ansible.builtin.apt:
    name:
      - zfsutils-linux
      - acl
    state: present

# No way to create pools using zfs ansible modules, so use direct command
# - name: Create ZFS pools
#   become: true
#   ansible.builtin.command:
#     cmd: zpool create {{ item.name }} {{ item.members }} -f
#     creates: /{{ item.name }}
#   loop: "{{ zfs_pools }}"
#   tags: ['zfs']

# Check for necessary zpools. Fail if not present. 
# (I don't think it's safe to automate the creation of zpools, as in the above command)
- name: Ensure ZFS pools are present
  ansible.builtin.command:
    cmd: "zpool status {{ item }}"
  loop: "{{ zfs_pools }}"
  when: zfs_pools is defined
  tags: ['zfs']

- name: Ensure ZFS datasets are present 
  become: true
  community.general.zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      acltype: posix
      xattr: sa
  loop: "{{ zfs_datasets }}"
  when: zfs_datasets is defined
  changed_when: false
  tags: ['zfs']

- name: Ensure ZFS datasets for containers are present 
  become: true
  community.general.zfs:
    name: "{{ container_config_zfs_id }}/{{ item }}"
    state: present
    extra_zfs_properties:
      acltype: posix
      xattr: sa
  loop: "{{ compose_list }}"
  when: compose_list is defined
  tags: ['zfs']
 
- name: Ensure dataset roots are owned by user
  become: true
  ansible.builtin.file:
    path: "/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0774
  loop: "{{ zfs_datasets }}"
  when: zfs_datasets is defined
  tags: ['zfs']