# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: 192.168.1.2
ansible_user: "{{ vault_server_username }}"

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: baremetal
host_name: deedee
host_city: ber
host_location: xberg
host_ipv4: 192.168.1.2
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"
host_description: "Runs infrastructure tasks"

# -------------------------------------------------------------------
# UBUNTU
# -------------------------------------------------------------------
ubuntupro_attach: true

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_bluetooth: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
host_primary_interface: "eth0"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    datasets:
      compositions:
        policy: critical
        children_inherit_policy: true
        datasets:
          awfulwoman:
            policy: none
          container-management:
            policy: none
          reverseproxy:
            policy: none
      acme:
        policy: critical
      terraform:
        policy: critical
      claude:
        policy: critical

# -------------------------------------------------------------------
# MISC
# -------------------------------------------------------------------

acme_path: "/fastpool/acme"
terraform_working_dir: "/fastpool/terraform"

# -------------------------------------------------------------------
# COMPOSITIONS
# -------------------------------------------------------------------
reverseproxy_use_letsencrypt: false

# -------------------------------------------------------------------
# REPOS
# -------------------------------------------------------------------

# The following repos will be pulled and made available at /opt/repos
repos:
  - repo: awfulwoman/infra
    name: infra
