vault_mailbox_domain: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          31373830616338663063313639633336306563666532626262663634353565616439626634613134
          6565356133316336353132646230313038313166343565300a636538323135643937356534363031
          30363364396462333163346365373234333265313961333935633635383364333737633761666333
          3061343061316331610a616561303465396430303231313136653464363536363832653064323730
          3232

vault_mailbox_user: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          63323166636631373333393162303061636663333437326262643338663433356265306534373335
          6664623065316262333962363735343031613731326438350a346463343565316461653461366665
          30656163303037343635346364643330346632346664383639353832303030666337366638663032
          3330386430386232370a303234616338323538616135653237623839303963353665326263633865
          34316631646531383938313763343461653164373563316265643230303465323962

vault_mailbox_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          35376236313936386436383033666535663431663138326261393134363066636266336538366632
          3133343436303138623261383561666639643563303931370a363839306665316461346435323231
          62373335303031336364386534636364663639626537336166383538393733376130326639373364
          3163613931623732610a333664333935656365623936326434353566323835313835643666643431
          35393263333835326532623132326661346665376166313235643330356161316134373435393330
          6261643361393930376533336264663834396138623562663931
