vault_claudecode_longlived_token: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          61343535653636373637366336333264326236346364653839366333316261633232353430383561
          6664623339613863353237306362623438306165306235630a383935613935656639373131343737
          38623565353630383034656138643936323534313464313165653264373036363366613263623531
          3866343430373230650a333337323935666138633062616535643939393532613162656364666366
          33643138343633623066313235666339336431323333663237653834316663666536616163346465
          32626236373131356164653263626135636531663463623738353736663831363830373131376437
          64343133363333393437653561643663653764303332356231333365623131346436353235346134
          35303632613935373866366363313738646663626566636539396436626436663362613335643966
          32626362313233393130373562376631656135633363363864393934643033306534
