vault_pixelfed_db_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          63616138333238656539633137623561633138666632306336393365633336343635363866333430
          6431633337346233343065366139303736333231303738620a336634663265356266633531326433
          30333037376261356533666630303764343963663337353765346633303861313261363630633264
          3765353639303934390a623736326530663765383265333237306361616434323661343931313566
          39393535653539643665316633636138376330303964633263616436313163663562326536333131
          3765313532306231633739393739313762623163333063323262

vault_pixelfed_app_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          34326535396264343962666364336635353039323063373334363139383661643431316265663335
          3063373038663966633932363463343930636138653135630a373732616431656437666130616135
          34333239323039663964376236646261376239653737373661626536653531313331626539306363
          3536313138343234660a343831323434366335346162356362313932303965316265646461366438
          34616136653866346432663230363633366632316661336339306334643632396661373735333538
          6630646664383234316566613762653765663433333965386537

vault_pixelfed_db_root_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          61363364353831623265396336656664306662383531653338613931353036653161393133646362
          6162336533666532666430653966396532393538663831320a663032303635653539346239303039
          66643634353630623939653461643539663864383661386537613631323966383639656361643661
          3838643630653933340a393937306439363232303864656132393765633261303062386438613861
          36666330383130353665376139393635303231313963663332306362343035343533333835393030
          6365333131363234633632373631373731626136393831326264
