vault_pixelfed_db_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          63616138333238656539633137623561633138666632306336393365633336343635363866333430
          6431633337346233343065366139303736333231303738620a336634663265356266633531326433
          30333037376261356533666630303764343963663337353765346633303861313261363630633264
          3765353639303934390a623736326530663765383265333237306361616434323661343931313566
          39393535653539643665316633636138376330303964633263616436313163663562326536333131
          3765313532306231633739393739313762623163333063323262

vault_pixelfed_app_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          30393964636466326332333533343063653634623065353935666531343564623363626661666134
          6238313862316638333064633738303530303063653163620a626533313266363764666161626265
          35383431326639306533643464336430343461333066373636366362383338353464393261313234
          3766316562656134350a646462306636373734653162343962633732386233306462616461643861
          62333434656134653832366335646431386564383430343639326339366466393138353334666466
          37316132633466333361346562373231343638613530623130323136613534336333393436623938
          333332626163373936636233366139373264

vault_pixelfed_db_root_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          61363364353831623265396336656664306662383531653338613931353036653161393133646362
          6162336533666532666430653966396532393538663831320a663032303635653539346239303039
          66643634353630623939653461643539663864383661386537613631323966383639656361643661
          3838643630653933340a393937306439363232303864656132393765633261303062386438613861
          36666330383130353665376139393635303231313963663332306362343035343533333835393030
          6365333131363234633632373631373731626136393831326264
