vault_mailbox_domain: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          31373830616338663063313639633336306563666532626262663634353565616439626634613134
          6565356133316336353132646230313038313166343565300a636538323135643937356534363031
          30363364396462333163346365373234333265313961333935633635383364333737633761666333
          3061343061316331610a616561303465396430303231313136653464363536363832653064323730
          3232

vault_mailbox_user: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          39323565386261393434393239623130373534323139613032326433636237643066663230343666
          6531633664373037303363643166623333623732363638370a663030313334663332376132363530
          36316663336365663036626132313233343666343664326263616135633937366663363831343637
          3361346533313436350a313238326365653838366232363164383362323661386437316262323434
          65356333356365343638623239346631313932386439336663613530663439396262

vault_mailbox_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          38656536636234323063373062363564393331313937636166343739653937363962633062383931
          6263386233343433396538666263303762313633313365660a356362633461643435653838663962
          39383064323738613934343037626263383839656266366538353736323962666431333865613864
          6163343366643637390a366132386532333337366235326136323866393931313263616432323761
          36613161643837346635353437646133366638326239353931353139366166303962306330363235
          6136303233633831626465343162386635366563626236656435