vault_mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38623539636263643739306436623337616237393233396639386437653532316363366461666363
          3737333865643762326634396362336430346533393766390a353837613162623730326464326232
          34343065303332653731656163386539633465383135333033623432326333643439306638376339
          6538333838346239370a313066663362363236373663626339343063393762623232616662303430
          35386264393165633739613065316465316139323133306364613464376335386630313465626237
          66313761333331653030306261336434373336363834333962383665663430383761643536653364
          306337373835623933656230336330656333
vault_wallabag_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62623833373839626633346462306132306433393566613963323639376166613564313630303433
          3066383561643731663936313430366264666534346238310a653938376133326465336336663063
          35643532633632373331313931326137656162656362383465636162346339373537306466346631
          3434303466636632350a663737656131643334323162303139333232343237353032613830313231
          35663231313238303030356539663736613137303336303464353835626634386232373431626234
          32643263613235323030386464663435303862333430346630636236373339633339303664303335
          613535373633333664613733356333316562
vault_ntfy_topic_systemhealth: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32636166366234643861333965313066613866306232343836303638313564306532646264386363
          3433616235363333383736333434373037666430336530360a633735353763636232373538613264
          37393964613237613633353135626564373663336433656166663430346461303966323361376230
          3163363438616630340a666339323962396638623163333362393637386136313630336131633661
          62656439356337636435343065306135656565303138373963343265636634323838
vault_gitea_runner_registration: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65613961343834333764373332373733616561623434306638313032383265626233383734306662
          3966326431346230376361346333656263643765366661380a386533396530363666363137656632
          61323739356639643736663265623735363433376165333661626439353238356262393961393639
          6232626433333538300a623536343962363263363763636433383936356564313162363865316262
          65366464643939373632333234343562306465366534366233313137373830643832626137373965
          6235626331373362646430343364323439336565363837626437
vault_karakeep_nextauth: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62363861663437333363333438613065626330396530653139636530653534663635323134326338
          3165343163643964376665393366353038313434346662630a326233623830356137646131623461
          39653433623838326562383963623265633939316132316663386333336266303031323436356139
          3233333166303835630a363237653764303934366563316135313866643630636332343232343734
          65313234313066303261393638616663366665393837616430656661313863613732313139303766
          37323131383264623964363534646663636333386266633731383362623631316138363934326366
          363736666664333630663933616366363631
vault_karakeep_meili: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61643235333061353535643465323261336338373764326266633365396631626530653734303032
          3761383738326630373263666463386433623431653436300a396261353036363562303862376139
          66353132373336323964653361306132356435366238383438353166376432666462373261353639
          6531616666343434390a383865366463306463303162363262643133383062323034633566623336
          39643462633934363236316661363364646236373766326431393564343131346366326635336465
          39616637643236363436663236363361636633643133356136666234346464356336636131633233
          646336666333633330663161646663623839
vault_karakeep_openai: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62313430353564333439633562333565336330313662633162316132396232326365656137326636
          3137643964623634383234343137373034643262623363360a353361333931616236326563303237
          30623265303732343564666536643261383762633966393235373936623563663966643431383666
          3332376164633831310a376636656338356632353733383139316332653265616136316230356535
          33333134336233613238343833313966343639383761373336326332643435363736376630393864
          36646535383339646332356462616133336633323739336431333436383066633334323964643164
          37383038313539613163373731373161646232383935646163303365303031393561646264666435
          66316239396665306265333338346134323165353433383737613461353630376239363263303639
          61666135376663663135653665633038303161633632393335363032663537626431643039373634
          62323061396431663466316539323636623332383039356365383966366133663730333664343862
          39633634353239316661633731356363656539376361623230643963363262363463303362396264
          39616461316538313035656164656336303662373963663763663830333562636433613633313939
          3363
vault_pinepods_pg_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33363932663333663230366332373037393732313764333434386435643964653232353934313635
          3337663962333637323138653637666163353764646230310a383236396632613464316464316465
          32316634356637633131663334623064326333323430643062316162363638323634383061653839
          3339616165393833340a663539646638373634306334333239663334393066363936633835663866
          66323637356564333537363039353538646339353834616235643033656436353830363861373037
          62373662663139613163656435636236336636646630386165373662313966353666386361346332
          613166666535393838653236383864613731
vault_pinepods_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34613338383335383165636535666265363965393564373330333830636430346163303066646138
          3762383237356361643761653335633435353737366162340a393136373239396430353231316261
          33633734333038326335613861616633316234316639343131376564393764333335333862333762
          6633326237356432370a356639333236316232373034623031373261623962323165313531313162
          36616561383861373037346635633138643166393630383032656339353362373061646465626630
          30616661643233663435303838666564373334313066386362323465353037326665356338376535
          653364393238616637633866383661363966
vault_pihole_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64333338626566623830643638646538653539666534633531346431373161626466643333396333
          3631323266376230353034616530396464613935383132330a383961373837366166363233633966
          39646465333163326437366436633737666664323232323330656266383630663034363666323830
          6639653834653333320a663231616563363535613266663838353366396462623139363161316230
          3130
vault_librofm_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66396664663830363232653734613936613161346136626665386134366562326564313735323135
          3531653564643633383831323636653239356462613439380a346438636139643131323033323934
          38333538666664636337666430663466313238323930386466306533383964613962356532323166
          6232623961623133350a396639333765383462653161613239333335636238663939316465323539
          39323039343132373936326436666438623437303630353662353962376163636431
vault_librofm_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39633336656165393232353732653335633431353536616232663461663132396161353866396434
          3131303533366435666331363631363361386363663732640a386532636562613837643362346131
          64646534623439333532323133343432373366336236646139336333333731386531393035623438
          3938386235333564370a623633313437656431626539616330343330623630653663383065623137
          39313037636436333064666566343666396238376566633834356664393933343332
vault_qbittorrent_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64656430636639346663353235646432633663633734336339326232316135373337326661353433
          3037306139313232666662653330313865343631623439650a666464323934636566353665313831
          37346566393865383830376537336263613033336336646538663462343136313861636165633639
          6162356435636431360a386333363530646161316334663137623631353964353137396633303034
          3035
vault_qbittorrent_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66393430313764633638633634626435333039313838386563646465343934346538346138643437
          3434653861366461313163393766633931303834363730660a333561313163366538616161613563
          32346237333264333133323539656465346463313362363166396339333461343061353766373737
          3864323534316362370a383566376261333666383039653732646536623134306664643030643739
          3461
vault_radarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386632613137663437356437343035643563623831316464373232313562393939623863376233
          3061333033383533333362663538626435313563336431380a623637306238363338373466363236
          66343232623833633664383161663565616366363263393363383864663432346339373461663962
          3562313962643833330a336264363530623030343737613466393832306634303131386463396262
          66326261663534633530613437613536623863616139346533326538393532613064376539653830
          3963303633303938376664633038646536616363383863326262
vault_sonarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33346337383934316137663736643232333864613137323164353239363666333964363865633563
          3263373230623630616565613035303937613865613530360a376561303031386436313231633265
          36396439386538353038636262326466343665663135316165373433353531356133306434646432
          3835646234636330370a613034303361313336636135363961653038653961613237303136333332
          61663733626435363932376230643564616536326331653163663231363766343862626636623231
          3131616336316539383362313066333161386132353239633634
vault_prowlarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31386330616364656630653139623436303832373830623961383632386336316332656435616639
          6138353732636663613930363333303831343835663636620a613937353331303363373539356333
          34306265666335356665643130636363363737663765643938643733393863356166646338636264
          3565616532613366630a366535323736663730646332333063386164386430656566383336383261
          63343333366362396637646332393337363766306130373836326435353738373534313535636563
          6361373331623834383537633761356464616232396530316238
vault_linkwarden_POSTGRES_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65333665353338313237343539386165343765643963613039303766303333633636643136666636
          6435616665376238393666656139303163383339306234610a366162316162353663316530613365
          64363066343931643266353262316638323439663838326434373439313031373661393033623465
          6137336331613865620a653465326534393237633563333638363537363364616362316134316365
          32623736333032343935336630316564393931373663643432636239326231656535623139323532
          6462363861396637306463616635653161366330353865396539
firefly_cron_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37666562396566383630616439656362393639646530316362653833356438663564646538383966
          3230373839326638316335616336363033333264386161370a303162646532396338393638326662
          65313434616339346339613931316230353737623662373539626266333833343036383639363265
          6336653462323833640a343966643634336161323534636161643036346631333866623035343438
          64383863626365316166373738323064303463393739356531383335313066313263393338613531
          3464343432313133616561356661303162303865636365303230
firefly_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66366134386565633038316634323839333962316532643538613731333230636232633464333162
          3533616638393238646330303834333630633135376662390a643534653033623934663839623964
          35353262616338316135316533393765626435316636623339323034333537653966326434303431
          6461666634643465340a333334613666363934306233396631353736373462343638363739343738
          33643135373837323139663661383765333261323232333063313933626363343832636436346664
          3430663539663731303134376436326562386430346635636362
firefly_app_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65666666386139623936626136636161376535653063316164373834316534373064373435666463
          6134323437626366383131633466356532383236366662370a326236623364333730343664393664
          64343239393835363765303862343063323038653931346265313936383332303234656164613162
          6538396662306563340a623264336534333539376463663935616135366562626335353437636464
          65303666383161626334633633303437326237306631396264636634353330633433643538343561
          3364323430343731393962323366383262616562383935653734

vault_grafana_admin_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          32656163396662386434333335383130393531313836333365333161356361653139313665376234
          3263373530643534336361653164333863333337613330300a663763393338343138386334313339
          35326266613630326663636662333135646430353062336634623235323938663037663939343163
          3038636230636161610a616130646462623735643162303636623430393536653239653032353062
          64656566363666303431363231626632356462373239613137646439623462653339
