vault_hetzner_api_key_rw: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          31343361616437623830313734646662356531633830326534303434333133346461623961326261
          3863363536633039313236376636623337623063393261350a353433333961333935306236333864
          37623031333265363338616436306361343334396261366332383032613035343134626533343563
          6664313539653039370a396239376132336636326335313562663739653964333435346536643531
          32623235623337366261323833636466323766373632356365623632643565393530393963363263
          65623839316434343661316233306238313964363862306632646337343234343130333964306561
          66326464396661623463386538363637383064653431393661313633643935323031353837663134
          33343230653764643962
