vault_tailscale_authkey: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          39633936393864656565613763326330353231356331373638613838653835343961386535343864
          3361383035643337643566616338623665303038326237310a333131313261653132613465356266
          39303839333664313364323137353832646331623861336636383564303961323161373965616637
          3038643266316362630a396161623937633839336237373931366435373061343530383464383731
          34376263646436366538323030633563623539313137626238663735353137333166616463326230
          35666634643932323666353832356136656364623136393334323437376237333664653333356338
          313566336565643263653132376530663632

tailscale_tailnet_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34306536666261653334663462366539373861363139386331333939613035626365396663393865
          3261633162613233613361323166383961313235626165620a373261643837333131326663333664
          39646136303433356436306462323662373730376330316161313830303663363337306166313932
          3030643064663562340a613536303137323933373634313637646532656430613134626135636662
          65666265353763363734633431643466663561373163393134656639306436303064
