vault_aws_backupuser_access_key_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32306334306336643238306432663761376531303132613664666265303739333962646631393436
          3761306430346138356265373832376662613665386334340a323030376362633361346537633963
          39316264633132666137353966303862373531313938366661313862383366616433336334643631
          3338616330386266370a636463623136366561636431663862613938333436313831356337663132
          65333538303938343139366664396163313737373164373164313161383461623966
vault_aws_backupuser_access_key_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30323538643332613936303866386166666630663262343230383062336132353932623736636432
          6538343634376461616439326366393961383166613465610a303064663932313937653639346536
          38343764316336313034343731373163336463663963303939303665626261366363356164656663
          3334393735633165620a383638663065333637306136316361386236643438383964333735653934
          61653336323334333061373361646133373638346133636631666366373430373032653164643831
          3964623830363930306137383965366463376634373766303636
vault_zigbee_network_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35303236643365343431643564396130356134386636366365633564373132306264616563623834
          6533306663393563363235313137356436373332396431640a363365386262663637336338343538
          31393663356165336131326236636330326130323930313764356465303738663533623539306466
          3737353137626363330a376339313036666131383836326664626562313336643237353732323934
          65386134316466316137343164303762613039653536383833373766306638306633326165333730
          65386531623632373966323833383337313363303832636632393830383165666637623434643663
          663236323433373465336430353431613264
vault_terraform_digitalocean_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38663363393863396330306339343439363763346137356332326234623466366136366230663930
          6334643866633033313935396438623264336666306238630a303735666631643838343362373833
          33323762653261373338383838366530653237386364373235336236633535376663663963343332
          3865643132623736340a346162663630393662323265653938646631623864393039396635323664
          65623365646431333364653039393962373461343237353561393430383138343436623735366334
          64313230383063313966393632633231626534363532383266373939373932346338613963626363
          31366137666430363936616432396434343035663165396438383936353665326130656566346463
          33336262366139323663
vault_ddns_digitalocean_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30383634623364353637346536336431333763616231323065613939346361373733303766336466
          3964303237623462383433363664343762666138623561620a306132656134333865653264336435
          36646631396230323731303866636338613133653130363866646232353237316335353432373136
          6335663561616330660a643463336563326361653531636337313931653662623764356131323335
          61383935356263663666303639366339623362333334316236333264366134323663636537343634
          38303436343862313236336239313337343361353038306562656532366263353630346236643062
          63613366363663383739313562633432623135616161323232313433336335393166643830376633
          33366633646666666337
vault_letsencrypt_digitalocean_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64646261386564366130363239363565316233366531363165303132666333336330633762303339
          3133383264346266646631386463343536386239333831620a303036303231326330396464336265
          64306634396337613464653832633566313931623939323231346531323133373062363966663662
          3565363431333763650a386133393264383366666337613166353936323766653136373133643535
          38646435653939373635323865663433383266303563656564353131646339623036663065336465
          36363538666237323035633262326464613139343463306562316532303462393061373838386264
          66366463656333356266623536366133363338636563313237623735323931646131656132643665
          35623633363632666464
vault_pushover_user_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32373739643535633431336131393932623338373065356238366534333135336336613139373065
          3637643733623466373039646138333838613361316231370a366332313361633261626335336133
          61323764633135643262613135396663376237343065316564313963386333316664383432393230
          3265333333653433650a316437336136333061386230343630646134393466343031323335393330
          39643930333332633264643936343932303436393139393665386532306231663963
vault_pushover_home_automation_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34366534336636356163393930353130353762633764333437363737656336656130343736313432
          6364343865373334643963663237353331373631636462310a356336313931346232306534656232
          38323036393563316136616666326565643862373231386362383461643462336632336363346430
          3865303131363332380a633330336337393365333835366564373462666639373036373061623566
          33636534666639623335353962636162633931353239336130636633633664633132
vault_pushover_home_network_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36636431613232303031316164333935313138623136396437643464636530303237633562636565
          3132636337393838373839626233373934343633323261390a356365303663626635353665383538
          36373563373935333230363039393562636462666635383366396539393737353036313163336462
          3739666537343833310a653035646538393334306439306638363762346266633830373461373834
          38306138346266643132653563343832396231333834353034326361396465666564
vault_homenetwork_ssid: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31356462326631343666376666663033306334313465633161643065646331343337313036316332
          3665663032333039633231363566663138346365386561370a386636363165663933356430343531
          62663936396461393031336364353533623234316162646563303633396635393463373861353335
          6662623039303861390a396232376632393732376132363961346362363734653538366430353466
          63326664313933636534646261373730363636623163356137646163356165613639
vault_homenetwork_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37333435626130646361336562303739323933633331656236386566396430616437356437386437
          6466616462356237366163373530636235393934386332660a613534373537633939636631333838
          31643130616331383565623539306537393665333732633132366262613937316566383238353630
          6432303465613365630a343362386131303630663761623733376231613234383939653662316238
          63383863633935366563316338393433343736366263343963636664346335633361

vault_docker_api_token_watchtower: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34373535313837363132666331613361613137356138633334346462323537383462646365393861
          6432303666663338623531373636333037343337316539360a656662656132636666356231396161
          30653465343735626538323134653463366231323930653831383063323430656630613138396134
          3166663863616434610a613835346330616463393833636230633664333832643763346639303033
          31656661653265626337646437343137316531303263313634613366313433306166343935343630
          3066353139393930666336303362386561343062643333393136
vault_mullvad_wireguard_private_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          32613066623939343032393262326432336161386130663134623163333566386634373035343235
          6137323730663432386536303036666338613939386636370a623362336439353838656261363062
          37666130393666373262303733643666373837356631346566323339393134636630373137363835
          3631653539303433650a356538366164663837653736393363333466343436336161373461386130
          66366231356434323133373637663762356232633337346562353639653434313230383532613930
          3762383965633131636436313564636437336331323466643763
vault_mullvad_wireguard_ipaddress: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          61623439343734616236666633636436636331313932666361623264643966323239376662663534
          3661623339623137353537643831303236333133643664340a303537336362343465623162386461
          64666566663466326630653962353463653266643063656565633664643963626361303036613438
          3236383233386134340a623530343362343135333061313036366336666138636438346630383561
          3633
vault_nordvpn_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65323534356232323337323236323630323136353335336332313839313637333933303732373836
          3861306362373862653536636364646162393131616630320a336264613266626230623466653734
          62333065336465373161323735313662663965346634393935633137353332353639313662333936
          3965313331373164340a643566366537646163316139336366373439356438363165366631653462
          30336436363532666161343462343662613135353963336362396135313661623831
vault_nordvpn_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36396465393266373063613832393935383637626138376133633332643166353238336139376131
          3636326435653331643737306439663761326234306366640a333632323861353837363462623232
          31666164303961336132373233643261356639386664306531613038393065323262313233323937
          3938386236646630330a646139643430666232343661646435663465383130323365353632613161
          37653933373730393034633338373462313237386561666338373237363864653361

vault_github_token_share_site: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37303537306364633039666632336335653532666662643565333239333835616330306239626666
          3838616665616339363236633563306537633764346562320a616464383037613735623262353631
          36363630336530326430343164656163363331653663643661653366613134626531356466663665
          3337303034383061610a646132303031383138643437316263626430303434303138623162386162
          35376438353662636430363139613335633334303965316161373132323232343632336233616364
          64656138616231386135663633386432363661383439326538353565353061623364623034393932
          38626662643336376661643837383161336662616430623561313331346230336631636264343937
          37396665663536373235376165623236663132326239353430663732303939343331393935653332
          3162
vault_admin_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62363332616262393534623961396235663033373338663464333035313065656165316264356334
          3039306264366564353464396332343431303835353538620a653562326437303833326133323464
          66353338343931313361636639336361633330353664313238653932333364313332666633333930
          3734653364313464380a656264326536643261666135663364343766393534333033323132383335
          66653830393939633939623134313662663639363335643137363237626463363336
vault_cert_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31383464633135383765643361356532366663373663303839306335646634653739316266336339
          6139613533306565363131343334656363656362653361630a336162633839613535343631373231
          35333163333230303537333435303633343433326233633333383738653962316638653465623530
          3730333430343031640a376134636466346266363265633832336633653463373565646364643532
          34326232653536323638616331363933326566383235656463636431636633396438
vault_personal_domain: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35626162643631386562343731666539303062633164393465613364353438626461336330376533
          3565653264633130396338663535653630643430323264340a613632316235356462323235396630
          32336537643065653337623063303263353731313633353131376138626537633263623932663163
          3235343562333663340a366531613836326666363833643966366532653765666465626336313262
          6434
vault_server_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30393036363965616337393739376633353433383939303765333234313263326338396634633732
          6263303266396665613361656434613563626633346131390a646536376336643538393536393262
          31666365326164373534306366613936316261366339663864386665326363323862356266656533
          3464623731653966390a623964626431313364613630346365323634363934326230343663303363
          3639
vault_digitalocean_domain_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30306632393236613233313938666562373435303362663038363561336166303535306530623333
          3963393938653336613637613833376337613932323331370a623032626639666535336532353466
          66316130623461353161343138393733383936626633643661306233626666326134363764333130
          3238373236356235620a396166636464386363303062386663633635366339386465653537363762
          32323139313366306232633739326131643337336138383936623965376136656163633361326166
          62646232346636643430303131383335636138343764643861643065313532366434366235626663
          61383566316565373533313733613035346363666432663561343134623739393130643639376239
          62636537333932343136
vault_digitalocean_full_access_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38623435313134336161373733383466633765303233373538396438636639366533373762393165
          3865366434646263353432383339353039656337333336300a613134373962656562306530376238
          30353831356561633832356662626431373061623131356130316333613463336465346432373238
          3365633030333238610a303539613366366261626536376335386163613138336336313337376263
          38326361393831363837363539643063656235646335366539393863313835323765373134626330
          39613736313362383265383231363135636365343861386466656464633133353530656564663565
          64643864613035363231306430356637613866646164646463346164326165376230323137633233
          64313665366265636236
vault_nut_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36363064646431393132626539383330623730353831333731303934323534323531386262663236
          3565316538613463303839623264613835383632363030350a313762306639323332663530326536
          61353766636465333530393662646663343932303639316361656632663466316139363432396435
          6233396262363038350a626138373731366561383039663732343434666636336437353934306430
          33616136336437623033336366306630323530636164393539653139373830336532
vault_smtp_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31343462636639623663353534626466333832663563643834323534653037363964333831323238
          3037653532663665656461613430346134343166613730360a346238303132646338353333363962
          38313065663262623464656565623137633431316563323033303839303363393430643965623533
          3539386161396438320a333663366365313737363631636261653531643137636334393030393836
          39323665656331653837633739643634353162313531366665326139363839613830
vault_smtp_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39306564666337313032633136626436626535336435376466306166633131333233656466333736
          3466643765346436636230613836393834356538663061610a303637643836366463363761336562
          61333738636362346261666532393930346563623263393462363765346439633635373434356232
          3465363664396439330a656434636530646164343534643766643733353839303335666231383833
          62393638396635383066613839646536643839323965366164616332613138643338616631383335
          3664326434303837383136313735383261613933373433373835
vault_smtp_host: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65616533383965343836333332613864376434316337386261366266343639636535383135623064
          6239633033666236343935366139356664383962376630640a343362323436343765383032376633
          64663832653462383935326434666638353837343730353539336165653464353535386662303737
          3434326236633738370a616331656433646331643031333464633162333239393333313464636439
          34313763326465386633323966393330366666323237326161353564643362613430
vault_amazon_locker_name_main: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64353439396465633931653530653136323735373132376531613038306261353537653864663231
          3639353730363539626261656330646366316337653333660a626232383638366464636637376430
          30616230663961393765663363393436323932653530633063353062633161323866353565663833
          3961343764343235610a356338643237386333623364343363323133313837393837373564336632
          6238

vault_healthchecks_rw_apikey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32356462653030663364373361656661646464336334336266373264656361613766656537333438
          3861346664393734353530333665303638336332636464380a373137363233313461346263613434
          34336339326161633738366336343365396436396530366635666565396136663038646533663830
          3464653338303338390a633139356164313764653635373666616166306265333564653433613939
          39653935373663376236626135323636623362326431366531666535316239303438366361353534
          6165633534343235613466636432386632323737393266633731
vault_digitalocean_letsencrypt_token: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          39663161343830663961393862646338663765303763616139343339393039313566323664666335
          3734383761343737663733656331303064666333373936380a633530376661633237376631623163
          65313964363537656565343437626536336464333666303535623365363839663031666336643837
          3638393936663930650a383762666365356664323266383435646161306231623031366564343866
          36306165613963316137343632623930363330396133623762373532633130316631653733373934
          32343062613935323863386138323935323039313736643439363936343163646635336563386539
          39363534356234643664343932306637666165343865303162323738313336346138346638666435
          36396365653330303234
