- name: Set variables
  ansible.builtin.set_fact:
    domain_base: "{{ item.domain }}"
    domain_sub: "{{ item.subdomain | default(false) }}"
    domain_sub_no_wildcard: "{{ (item.subdomain | split('.') | reject('match', '[*]') | join('.')) if item.subdomain is defined else false }}"
    domain_full: "{{ item.subdomain + '.' if item.subdomain is defined }}{{ item.domain }}"

- name: INFO ðŸ’‹
  ansible.builtin.debug:
    msg: "Assessing {{ domain_full }} - Cert {{ ansible_loop.index }}/{{ ansible_loop.length }}"

- name: Check for existing CSR private key
  ansible.builtin.stat:
    path: "{{ infra_certbot_csr_private_key_filename }}/{{ infra_certbot_csr_private_key_filename }}"
  register: csr_key

- name: Generate CSR private key if not present
  community.crypto.openssl_privatekey:
    path: "{{ infra_certbot_csr_private_key_dir }}/{{ infra_certbot_csr_private_key_filename }}"
    curve: secp521r1
    state: present
  when: not csr_key.stat.exists

- name: Check for existing CSR file
  ansible.builtin.stat:
    path: "{{ infra_certbot_csr_dir }}/{{ domain_full }}.csr"
  register: csr_file

- name: Generate an OpenSSL CSR if not present
  community.crypto.openssl_csr:
    path: "{{ infra_certbot_csr_dir }}/{{ domain_full }}.csr"
    privatekey_path: "{{ infra_certbot_csr_private_key_dir }}/{{ infra_certbot_csr_private_key_filename }}"
    common_name: "{{ domain_full }}"
  when: not csr_file.stat.exists

- name: Check for existing cert
  ansible.builtin.stat:
    path: "{{ infra_certbot_cert_dir }}/{{ domain_full }}.crt"
  register: cert_file

- name: Retrieve renewal information for existing certificate
  community.crypto.acme_ari_info:
    acme_directory: "{{ infra_certbot_dir }}"
    acme_version: "{{ infra_certbot_version }}"
    certificate_path: "{{ infra_certbot_cert_dir }}/{{ domain_full }}.crt"
  when: cert_file.stat.exists
  register: cert_data

- name: Debug cert_data
  ansible.builtin.debug:
    var: cert_data
  when: infra_certbot_debug

# - name: Set variables
#   ansible.builtin.set_fact:
#     cert_exists: "{{ cert_file.stat.exists }}"
#     cert_requires_renewal: "{{ ansible_date_time.iso8601 > cert_data.renewal_info.suggestedWindow.start }}"

- name: NEW CERT - DNS01
  when: not cert_file.stat.exists
  ansible.builtin.include_tasks:
    file: dns01.yaml
  vars:
    dns01_domain_base: "{{ domain_base }}"
    dns01_domain_sub: "{{ domain_sub }}"
    dns01_domain_sub_no_wildcard: "{{ domain_sub_no_wildcard }}"
    dns01_domain_full: "{{ domain_full }}"
    dns01_domain_full_no_wildcard: "{{ domain_full | split('.') | reject('match', '[*]') | join('.') }}"

- name: RENEW CERT - DNS01
  when: (cert_file.stat.exists) and (ansible_date_time.iso8601 > cert_data.renewal_info.suggestedWindow.start)
  ansible.builtin.include_tasks:
    file: dns01.yaml
  vars:
    dns01_domain_base: "{{ domain_base }}"
    dns01_domain_sub: "{{ domain_sub }}"
    dns01_domain_sub_no_wildcard: "{{ domain_sub_no_wildcard }}"
    dns01_domain_full: "{{ domain_full }}"
    dns01_domain_full_no_wildcard: "{{ domain_full | split('.') | reject('match', '[*]') | join('.') }}"
