vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          32396263343337356634366636303731363135303465353734373633353564336332386561363463
          3335353937363566303430373837393435326235643566630a346563343435333237313863623236
          36636133663363353562656664303961646332303363353233366636383931383439666339623438
          6334306162613839660a373538323830393064376462383936313237396238323731353663383962
          34616661366266613930373333386333396162313633643731643838643931353766373035643231
          3364313862336266393639653634383064623039356265366433

vault_zfs_passphrase: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          32613333643665626131613331313839613664323934353036666339663630656364346530326532
          3034366638623139623936623734366433303632383165360a373032623234343066346135366137
          33333964386261643865343437383763633239303261343436626163373633323233653434383235
          6639623266623633380a383936666562353530663162333265313563313262653761656430356462
          31636536333463336330383535636233366164396263623661346138393063633861303939383631
          62613564386438666365363966343464386439356266316236326239323137373963636466373437
          613263306430383434623465613564333034
