- import_playbook: dns/core.yaml
- import_playbook: host-storage/core.yaml
- import_playbook: host-homeassistant/core.yaml
- import_playbook: host-albion/core.yaml
- import_playbook: router/core.yaml
- import_playbook: pikvm/core.yaml
