vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          39616536316662663739363136336466393865363738633234313332623962613433373633623038
          3738383536383266346366633532656436636337346533610a636166356133323761613661623439
          37653630623734393031396533313533386264333136346665643138643563386565343232363733
          6261333031633362610a376433653231326564623639663330386463393265363866376438613130
          64343734663535653339626131373431363362623236306232396438323039393039326465343137
          3864666664396164666664616138613538313238653039626438
