ansible_host: awfulwoman.com
ansible_user: "{{ vault_server_username }}"

host_type: virtual
host_name: sites
host_city: hetzner
host_location: cloud
host_ipv4: 188.245.37.81
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"
host_description: "Hetzner cloud server for public services"

bootstrap_ubuntu_timezone: "Europe/Berlin"

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
configure_dns_linkdevice_physical: "eth0"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    device:
    vdevs:
      - type: stripe
        disks:
          - /dev/disk/by-id/scsi-0HC_Volume_104390137
    datasets:
      compositions:
        policy: critical
      sites:
        datasets:
          awfulwoman:
            policy: critical
          pixelfed:
            policy: critical
          gotosocial:
            policy: critical

# -------------------------------------------------------------------
# SITES
# -------------------------------------------------------------------

traefik_providers:
  - gotosocial
