- name: Storage NAS
  hosts: host-storage
  vars:
    compositions:
      - syncthing
  roles:
    - role: system-zfs-policy
  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
