- name: Storage NAS
  hosts: host-storage
  vars:
    compositions:
      - syncthing
  roles:
    # - role: infra-private-resources
    # - role: script-share-personal-site
    # - role: system-pipx
    - role: infothrill.nullmailer
      become: true

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
