- name: Storage NAS - VictoriaMetrics & Grafana
  hosts: host-storage

  roles:
    - role: composition-victoriametrics
    - role: composition-grafana


  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
