# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: host-backups
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# INFRA
# -------------------------------------------------------------------
host_type: baremetal
host_name: backups # Hostname of the machine
host_city: ber # City where the machine is located
host_location: xberg # Location of the machine within the city
host_ipv4: 192.168.1.118
host_pfqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}"
host_fqdn: "{{ host_name }}.{{ host_location }}.{{ host_city }}.{{ domain_name }}"

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
host_primary_interface: "enp3s0"
host_ipv4_subnet: 24
wakeonlan_mac_address: "60:a4:4c:40:52:57"
# configure_dns_linkdevice_physical: "enp3s0"
wakeonlan_interface: enp3s0

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

# Experimental
zfs:
  slowpool:
    vdevs:
      - type: mirror
        disks:
          - /dev/disk/by-id/scsi-SATA_ST2000DM008-2FR1_ZK308FPE
          - /dev/disk/by-id/scsi-SATA_ST2000DM008-2FR1_ZK308GLF
      - type: mirror
        disks:
          - /dev/disk/by-id/scsi-SATA_ST2000DM008-2FR1_ZK308JA0
          - /dev/disk/by-id/scsi-SATA_WDC_WD20EZAZ-00L_WD-WX82AB005EXH
    datasets:
      compositions:
      encryptedbackups:
        state: present

# -------------------------------------------------------------------
# COMPOSITIONS
# -------------------------------------------------------------------
compositions:
  - zfs-api
