vault_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          34373765353433306666663731623731313739343461373831346331326330383736333138386565
          6666393966323363343234613631613336636361626434360a373737616161393735306539633736
          30653432396332303931643130326362313866376232653330343134336266653639663437393663
          3736643838363236360a383733653461336266326133626434373938633731636535393364333535
          39316334646138353430623831323065313366393435306239613535323439623961643765326139
          3236643537383030663161646638646335373133343935363733

vault_zfs_passphrase: !vault |
          $ANSIBLE_VAULT;1.2;AES256;beanpod
          32303436643438333862313134616130636161376566363564346632616632306162636234616262
          6430303334346438666263303533663362636262336633350a393464656264396162643135383439
          64313261393062333135613633326163323166393433653862366130393135613436626165643134
          3139663566376264330a333738333732333261343930646366666139356334663265353061343164
          65333737646138333465376631653931316131316164326338396262393364633038643234646331
          32656634396636643231393333613261376364626637366261363262393764626263303734656334
          36626233613833623166323430646637666631343039323965636465646163663236373430373161
          34366236643837326538
